name: mtlc

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- mtl
- haskeline

library:
  source-dirs: src

executables:
  mtlc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtlc

tests:
  mtlc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtlc
